language: python

python:
   - 3.6

services:
  - xvfb

branches:
    only:
        - master
# commands to prepare the conda install - download the latest conda
# and install it and add to path
before_install:
    - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - source $(conda info --root)/etc/profile.d/conda.sh

install:
   - pip install -r requirements.txt
   - conda config --set restore_free_channel true
   - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
   - conda activate test-environment
   - conda install --yes coverage coveralls flake8


# for production, remove the --exit-zero
# this side-steps failing build on PEP8 violations
before_script:
   - "export DISPLAY=:99.0"
   - flake8 frxas --exclude=*.ipynb_checkpoints

script:
   - pytest --cov=frxas frxas/tests

after_success:
   - coverage report
   - coveralls
