# Built using template from @dacb
# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
matrix:
    include:
        # - python: 3.5
        - python: 3.6
        # - python: 3.7

# what branches should be evaluated
branches:
    only:
        - master

# commands to prepare the conda install - download the latest conda
# and install it and add to path
before_install:
    - wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

services:
  - xvfb

# list of commands to run to setup the environment
install:
    - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment2.yml
    - source activate test-environment
    - conda install --yes coverage coveralls flake8
    # - pip install -r requirements.txt

# a list of commands to run before the main script
before_script:
   - "export DISPLAY=:99.0"
   - flake8 frxas --exclude=*.ipynb_checkpoints

# the actual commands to run
script:
   - nosetests --with-coverage --cover-erase --cover-package=frxas

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls