name: frxas
channels:
  - GSECARS
  - defaults
  - conda-forge
dependencies:
  - asteval
  - blas
  - ca-certificates
  - certifi
  - cycler
  - freetype
  - h5py
  - hdf5
  - icc_rt
  - icu
  - intel-openmp
  - jpeg
  - kiwisolver
  - libpng
  - lmfit
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - openssl
  - pip
  - pyparsing
  - pyqt
  - pyreadline
  - python
  - python-dateutil
  - qt
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tornado
  - uncertainties
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - zlib


